services:
  scala-bank-db:
    container_name: scala-bank-db
    image: postgres:13.1
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "postgres", "-U", "postgres" ]
      timeout: 45s
      interval: 10s
      retries: 10
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ${PWD}/docker/scala-bank-db/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - ${PWD}/pg-data:/var/lib/postgresql/data/
    ports:
      - 6900:5432
    networks:
      - scala-bank-network

networks:
  scala-bank-network:
    name: scala-bank-network
